config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "pets", to: "pets#index"

  get "pets/new", to: "pets#new", as: :new_pet
  post "pets", to: "pets#create"

  get "pets/:id", to: "pets#show", as: :pet


  get "pets/:id/edit", to: "pets#edit", as: :edit_pet
  patch "pets/:id", to: "pets#update"

  delete "pets/:id", to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["Dog", "Cat", "Snake", "Bird", "Fish"]
  validates :name, presence: true
  validates :species, inclusion: {in: SPECIES}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  
  def index
    @pets = Pet.all
  end


  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pets_path
  end

  def show
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, Pet::SPECIES %>
  <%= f.label :found_on %>
  <%= f.date_field :found_on %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %></h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>See all lost pets !</h1>

<ul>
  <% @pets.each do |pet|  %>
  <li>
    <%= pet.name %> | <%= pet.species %>
  </li>
  <% end %>
</ul>

<%= link_to new_pet_path do%>
  <i class="fa-solid fa-pen"></i> Create a pet
<% end %>

app/views/pets/new.html.erb
<h1>Add a new pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1>Details of the pet</h1>

<p><%= @pet.name %></p>
<p><%= @pet.species %></p>
<p><%= @pet.address %></p>
<p><%= @pet.found_on %></p>

<%= link_to "Delete", pet_path(@pet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger"  %>
<%= link_to "Edit",  edit_pet_path, class: "btn btn-warning"%>
<%= link_to "All pets", pets_path, class: "btn btn-primary"  %>